name: continuously run gitgat

on:
  #remove the following commented lines to enable continuous running
  #schedule:
  #- cron: "0 23 * * *"
  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env: 
      GITHUB_SECRET : ${{secrets.GH_SECRET}}
    steps:
    
    # checkout in order to have state
    - uses: actions/checkout@v3
    
    # run gitgat
    - name: run GitGat
      run: |
        docker pull scribesecurity/gitgat:latest
        docker run -e "$GITHUB_SECRET" -v $(pwd):/var/opt/opa scribesecurity/gitgat:latest data.github.report.print_report 2> report.md
      
    # push report to artifacts of pipeline run  
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: gitgat report
          path: report.md

    # Push updates to repo. To enable uncomment the following lines.
#     - name: Push updated report.md to repo
#       run: |
#           cp report.md tmp.md
#           git config --global user.name "My name (via get_latest workflow)"
#           git config --global user.email "nobody@nowhere.com"
#           git rm report.md
#           git commit -m "remove tmporarly report"
#           mv tmp.md report.md
#           git add report.md
#           git commit -m "report.md"
#           git push
  
      
      
    
    
